(function initYouTubeUtils(global) {
  "use strict";

  const VIDEO_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;

  function getVideoId(input) {
    try {
      const url = input instanceof URL ? input : new URL(String(input));
      const host = url.hostname.replace(/^www\./, "");
      let id = "";

      if (host === "youtu.be") id = url.pathname.split("/").filter(Boolean)[0] || "";
      else if (host.endsWith("youtube.com")) {
        if (url.pathname === "/watch") id = url.searchParams.get("v") || "";
        else {
          const match = url.pathname.match(/^\/(?:shorts|live|embed)\/([^/?#]+)/);
          id = match ? match[1] : "";
        }
      }

      return VIDEO_ID_PATTERN.test(id) ? id : null;
    } catch (_error) {
      return null;
    }
  }

  function textFromRuns(value) {
    if (!value) return "";
    if (typeof value === "string") return value;
    if (typeof value.simpleText === "string") return value.simpleText;
    if (Array.isArray(value.runs)) return value.runs.map((run) => run && run.text || "").join("");
    return "";
  }

  function trackKey(track) {
    return [track.languageCode, track.kind || "manual", track.vssId || "", track.name || "", track.baseUrl || ""].join("|");
  }

  function normalizeTracks(rawTracks) {
    const seen = new Set();
    const languageCounts = new Map();
    const preliminary = [];

    for (const raw of Array.isArray(rawTracks) ? rawTracks : []) {
      if (!raw || typeof raw.baseUrl !== "string" || !raw.baseUrl.startsWith("https://www.youtube.com/api/timedtext")) continue;
      const languageCode = String(raw.languageCode || "und");
      const isAutoGenerated = raw.kind === "asr" || String(raw.vssId || "").startsWith("a.");
      const name = textFromRuns(raw.name) || languageCode;
      const track = {
        baseUrl: raw.baseUrl,
        languageCode,
        name,
        kind: raw.kind || "",
        vssId: raw.vssId || "",
        isAutoGenerated,
        isTranslatable: Boolean(raw.isTranslatable)
      };
      const key = trackKey(track);
      if (seen.has(key)) continue;
      seen.add(key);
      preliminary.push(track);
      languageCounts.set(languageCode, (languageCounts.get(languageCode) || 0) + 1);
    }

    return preliminary.map((track) => {
      const type = track.isAutoGenerated ? "自动生成" : "人工字幕";
      const showType = track.isAutoGenerated || languageCounts.get(track.languageCode) > 1;
      return { ...track, label: showType ? `${track.name}（${type}）` : track.name };
    });
  }

  function extractVideoData(playerResponse, expectedVideoId) {
    if (!playerResponse || typeof playerResponse !== "object") return null;
    const details = playerResponse.videoDetails || {};
    const videoId = details.videoId || expectedVideoId || "";
    if (expectedVideoId && videoId && expectedVideoId !== videoId) return null;

    const renderer = playerResponse.captions &&
      playerResponse.captions.playerCaptionsTracklistRenderer;
    const tracks = normalizeTracks(renderer && renderer.captionTracks);
    return {
      videoId,
      title: details.title || "YouTube Video",
      tracks,
      translationLanguages: Array.isArray(renderer && renderer.translationLanguages)
        ? renderer.translationLanguages.map((item) => ({
            languageCode: item.languageCode || "",
            name: textFromRuns(item.languageName) || item.languageCode || ""
          })).filter((item) => item.languageCode)
        : []
    };
  }

  function sanitizeFilenamePart(value, maxLength) {
    const limit = Number.isFinite(maxLength) ? maxLength : 120;
    let result = String(value || "")
      .normalize("NFC")
      .replace(/[<>:"/\\|?*\u0000-\u001F]/g, " ")
      .replace(/[\s\u00A0]+/g, "_")
      .replace(/_+/g, "_")
      .replace(/^[._\s]+|[._\s]+$/g, "");

    if (!result) result = "YouTube_Subtitles";
    const chars = Array.from(result);
    if (chars.length > limit) result = chars.slice(0, limit).join("").replace(/[._\s]+$/g, "");
    return result;
  }

  function buildFilename(title, language) {
    const safeLanguage = truncateUtf8(sanitizeFilenamePart(language, 36), 48);
    const titleBudget = Math.max(48, 220 - 1 - utf8Length(safeLanguage));
    const safeTitle = truncateUtf8(sanitizeFilenamePart(title, 110), titleBudget);
    return `${safeTitle}_${safeLanguage}.txt`;
  }

  function utf8Length(value) {
    return Array.from(String(value || "")).reduce((total, char) => {
      return total + (encodeURIComponent(char).match(/%[0-9A-F]{2}|./gi) || []).length;
    }, 0);
  }

  function truncateUtf8(value, maxBytes) {
    let result = "";
    let bytes = 0;
    for (const char of Array.from(String(value || ""))) {
      const size = utf8Length(char);
      if (bytes + size > maxBytes) break;
      result += char;
      bytes += size;
    }
    return result.replace(/[._\s]+$/g, "") || "YouTube_Subtitles";
  }

  global.SubtitleExporterYouTube = {
    getVideoId,
    textFromRuns,
    normalizeTracks,
    extractVideoData,
    sanitizeFilenamePart,
    utf8Length,
    truncateUtf8,
    buildFilename
  };
})(typeof globalThis !== "undefined" ? globalThis : window);
